### ISSUE TITLE
Consider raising hackney's recv_timeout

### ISSUE THREAD

**Issue by hamann** [sikanhe/acme#1]
Please consider raising hackney's `recv_timeout` which defaults to 5 seconds. Often our renew process aborts because of this low default value

```
** (MatchError) no match of right hand side value: {:error, :timeout}
    (acme) lib/acme/client.ex:172: Acme.Client.request/2
```

**Comment by sikanhe** [comment]
@hamann  Would it be better to allow to pass that as an option for Acme.request? 
Also, you are using this lib in production? :O

**Comment by hamann** [comment]
Whatever helps :)

Yes, we do. Needed to add some workarounds because the current ssl implementation doesn't support multiple SAN's, but otherwise it works quite well :)

**Comment by sikanhe** [comment]
@hamann fixed with https://github.com/sikanhe/acme/pull/2 :) Will put out a release soon.
