### ISSUE TITLE
Update hackney dependency version?

### ISSUE THREAD

**Issue by DavidOliver** [sikanhe/acme#3]
Thanks for acme. I'm building a little tool/app to register certificates using the DNS challenge type, and all is going well so far. :)

To make updating DNS via Cloudflare's API easier I've added httpoison, but I had to use an old version because acme currently defines hackney 1.7.1 as a dependency rather than the latest 1.8. Would updating the dependency be possible?

**Comment by sikanhe** [comment]
@DavidOliver Apologize for the delay, deps are updated in the latest version (0.4.1)
